#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SQLAlchemy-Utils
Version  : 0.33.3
Release  : 23
URL      : https://files.pythonhosted.org/packages/28/17/fedf5a8b2492a7d12986273b7d661419970b1866f3be3f897114aa3c7195/SQLAlchemy-Utils-0.33.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/28/17/fedf5a8b2492a7d12986273b7d661419970b1866f3be3f897114aa3c7195/SQLAlchemy-Utils-0.33.3.tar.gz
Summary  : Various utility functions for SQLAlchemy.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: SQLAlchemy-Utils-python3
Requires: SQLAlchemy-Utils-license
Requires: SQLAlchemy-Utils-python
Requires: Babel
Requires: Jinja2
Requires: Pygments
Requires: SQLAlchemy
Requires: anyjson
Requires: cryptography
Requires: docutils
Requires: enum34
Requires: flake8
Requires: ipaddr
Requires: isort
Requires: passlib
Requires: psycopg2
Requires: pytest
Requires: python-dateutil
Requires: python-mock
Requires: pytz
Requires: six
BuildRequires : SQLAlchemy
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
SQLAlchemy-Utils
        ----------------
        
        Various utility functions and custom data types for SQLAlchemy.

%package license
Summary: license components for the SQLAlchemy-Utils package.
Group: Default

%description license
license components for the SQLAlchemy-Utils package.


%package python
Summary: python components for the SQLAlchemy-Utils package.
Group: Default
Requires: SQLAlchemy-Utils-python3
Provides: sqlalchemy-utils-python

%description python
python components for the SQLAlchemy-Utils package.


%package python3
Summary: python3 components for the SQLAlchemy-Utils package.
Group: Default
Requires: python3-core

%description python3
python3 components for the SQLAlchemy-Utils package.


%prep
%setup -q -n SQLAlchemy-Utils-0.33.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532378721
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/SQLAlchemy-Utils
cp LICENSE %{buildroot}/usr/share/doc/SQLAlchemy-Utils/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/SQLAlchemy-Utils/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
