#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SQLAlchemy-Utils
Version  : 0.32.14
Release  : 21
URL      : https://pypi.debian.net/SQLAlchemy-Utils/SQLAlchemy-Utils-0.32.14.tar.gz
Source0  : https://pypi.debian.net/SQLAlchemy-Utils/SQLAlchemy-Utils-0.32.14.tar.gz
Summary  : Various utility functions for SQLAlchemy.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: SQLAlchemy-Utils-python
Requires: Babel
Requires: Jinja2
Requires: Pygments
Requires: SQLAlchemy
Requires: anyjson
Requires: cryptography
Requires: docutils
Requires: enum34
Requires: flake8
Requires: isort
Requires: passlib
Requires: psycopg2
Requires: pytest
Requires: python-dateutil
Requires: python-mock
Requires: pytz
Requires: six
BuildRequires : SQLAlchemy
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six

%description
SQLAlchemy-Utils
================
|Build Status| |Version Status| |Downloads|
Various utility functions, new data types and helpers for SQLAlchemy.

%package python
Summary: python components for the SQLAlchemy-Utils package.
Group: Default
Provides: sqlalchemy-utils-python

%description python
python components for the SQLAlchemy-Utils package.


%prep
%setup -q -n SQLAlchemy-Utils-0.32.14

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492438383
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492438383
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
